"""Add vector column to youtube_knowledge_chunk

Revision ID: 45c4ac899d96
Revises: fa51fd3fd00c
Create Date: 2026-04-29 10:14:27.608820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector 

# revision identifiers, used by Alembic.
revision: str = '45c4ac899d96'
down_revision: Union[str, Sequence[str], None] = 'fa51fd3fd00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_knowledge_chunk', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_knowledge_chunk', 'embedding')
    # ### end Alembic commands ###
