"""add new table and column

Revision ID: fa51fd3fd00c
Revises: a9886e977674
Create Date: 2026-04-23 10:29:36.685568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa51fd3fd00c'
down_revision: Union[str, Sequence[str], None] = 'a9886e977674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_channel_identity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index(op.f('ix_user_channel_identity_user_id'), 'user_channel_identity', ['user_id'], unique=False)
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('user', 'is_active')
    op.drop_index(op.f('ix_user_channel_identity_user_id'), table_name='user_channel_identity')
    op.drop_table('user_channel_identity')
    # ### end Alembic commands ###
